language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  user: __token__
  password:
    secure: pTyRyNnejg9+xr32IC7GEMVSQRfLQbzP5Eqa7IvWtMcrAvr1/jW6b3cj+z5fCkjrI8XjQ/Io9NXo5ZjKhl5UcrmXG3SLIpBEDlYMEcF9YXEB1Sm3keuQVPRsIgyC/gQhalSQw8gryQB3RSxTzwaWsM9D6a1hW5QlCvaD7SMnBVv8gIvqLAhv08VDIWWoe87xOLESucNN4RQZzXQFSnT8Sbe1V6FyC1puHL5bdt4MMn/8SzlISyA3M4RaxeHNWzV6HqzDqP6gAvr0x6CMyhkgxrpdl6Ak2Jl8naRk1VLx+zP7mksV3crFwoENgsX6wm4Z4y1qHkC14qkhrl1Xnjvoz5jvTwEqQe/iowLA6IfYRYkk3Z8QiVRtZ2iXdGFAh1ZbxY6iaw8NbXOmG7Q3BmwHAlNFhBBOR8N0sGTpO2GGKnmen44iRKILYddFgITfJlmUyQSzS7CmC5h5Co965FiiuujwefHUhEsDNWsTlUwoXhykUyCCOoGO8vOJAYJilCcPGCx/mZRcleXYbZy0HpMvm+b64+Rj7l47slbY07bCQptkxKwGOkWW+I/eLWngKkZaVOcVMySF9IG+KcAXzB/H+Fquce/FncjLXzV5HEfyTu0U5JXeyI5RXObycFVHbCEKDddUHzoi3NdOtHC6G16Ou7uC/691hbCdCW0EQ5wgv8U=
  on:
    tags: true
    repo: anton-b/alcli
    python: 3.8
